"""create tables

Revision ID: 404fa70bcf2c
Revises: 
Create Date: 2017-05-05 14:30:11.289634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404fa70bcf2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('is_crawl', sa.Enum('yes', 'no'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_pool')
    op.drop_table('baike')
    # ### end Alembic commands ###
